### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by gffernandez** [gffernandez/SEBC#2]

**Comment by mfernest** [comment]
Could you comment on your progress with this lab so far?

**Comment by gffernandez** [comment]
I committed my Installation scripts now.

**Comment by gffernandez** [comment]
completed

**Comment by mfernest** [comment]
Did you use the same message for every commit to your repo? Very confusing.

**Comment by mfernest** [comment]
Database server replication lab not submitted.
